#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  if [[ "$#" == 0 ]]; then
    set +f
    set -- /data/git/cache/*/*/*
    set -f
  fi

  runmany 10 'unset GIT_SSH; cd $1; git fetch --all' "$@"
}

source sub "$BASH_SOURCE" "$@"
