#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  local pth_install="$1"; shift
  local key_install="$(echo "$pth_install" | perl 's{[_-\W]+}{-}g')"
  local pth_cache_install="${DATA}/cache/install/${ID_INSTALL}-${key_install}"

  if [[ ! -f "$pth_cache_install" ]]; then
    return 1
  fi

  (cd / && tar xfz "$pth_cache_install")
  return 0
}

source sub "$BASH_SOURCE" "$@"
