#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ ! -x "$(which pkg 2>/dev/null || true)" ]]; then
    return 0
  fi

  case "$(uname -s)" in
    Linux)
      env CFLAGS=-O2 pkg ensure www/squid www/squid3
      ;;
    *)
      pkg ensure www/squid www/squid3
      ;;
  esac

  if [[ -d "$PKG_HOME" ]]; then
    mkdir -p "$PKG_HOME/install/var/squid/cache/squid"
  fi
}

bootstrap
