#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Linux)
      env CFLAGS=-O2 pkg ensure www/squid www/squid3
      ;;
    *)
      pkg ensure www/squid www/squid3
      ;;
  esac

  mkdir -p "$PKG_HOME/install/var/squid/cache/squid"
}

bootstrap
