#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -w /data/git/cache && -w /data/git ]]; then
    return 0
  fi

  return 1
}

main "$@"
