#!/usr/bin/env bash

function profile {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  PATH="$shome/bin:$PATH"

  export BASEBOX_CACHE="/vagrant"

  if [[ -n "${ssh_gateway:-}" ]]; then
    export GIT_SSH="$(which cache-git 2>/dev/null)"
    if [[ ! -x "$GIT_SSH" ]]; then
      unset GIT_SSH
    fi
  fi
}

profile
