#!/usr/bin/env bash

function profile {
  local shome="${_cache_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"

  export CACHE_VIP='172.28.130.2'

  export BASEBOX_CACHE="/vagrant"

  if [[ -n "${ssh_gateway:-}" ]]; then
    export GIT_SSH="$(which cache-git 2>/dev/null)"
    if [[ ! -x "$GIT_SSH" ]]; then
      unset GIT_SSH
    fi
  fi
}

profile
