#!/usr/bin/env bash

function stale {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -x "$(type -P squid)" ]]; then
    return 1
  fi

  return 0
}

stale
