#!/usr/bin/env bash

function home_update {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  install -dv -m 0755 "$CACHE_DIR"

  if ! facts -e '(.virtualization_role == "guest")' >/dev/null; then
    if ! ifconfig -a | grep "${CACHE_VIP}" >/dev/null; then
      case "$(uname -s)" in
        Darwin)
          sudo ifconfig en0 alias "${CACHE_VIP}/24" up
          ;;
        Linux)
          sudo ip addr add "${CACHE_VIP}" dev lo
          ;;
      esac
    fi
  fi
}

home_update "$@"
