#!/usr/bin/env bash

function home_update {
  local shome="${_cache_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  install -dv -m 0755 "$BASEBOX_CACHE"
}

home_update "$@"
